#!/usr/bin/env node
// Developer-only build. Users run the supplied classic js/game.js without Node.
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createRequire} from 'node:module';
const root=fileURLToPath(new URL('../',import.meta.url));
let esbuild;
try {esbuild=await import('esbuild');}
catch {const dir=process.env.SMARTACTION_BUILD_TOOLS;if(!dir)throw new Error('Run npm install, or set SMARTACTION_BUILD_TOOLS to a node_modules directory.');esbuild=await import(pathToFileURL(createRequire(path.join(dir,'package.json')).resolve('esbuild')).href);}
const {locations}=await import('../data/locations.js');
const photos={};for(const place of locations)if(place.photo&&!/^https?:/.test(place.photo))photos[place.id]='data:image/jpeg;base64,'+(await fs.readFile(path.join(root,place.photo))).toString('base64');
await fs.writeFile(path.join(root,'js/offline-photos.js'),'// Generated by tools/build.mjs from attributed local photos.\nexport const offlinePhotos='+JSON.stringify(photos)+';\n');
await esbuild.build({entryPoints:[path.join(root,'js/app.js')],bundle:true,format:'iife',platform:'browser',target:['es2020'],outfile:path.join(root,'js/game.js'),minify:true,legalComments:'eof',define:{'import.meta.url':'"file:///source-module-only/"'},banner:{js:'/* SmartAction v2 · classic entry supports file://. Source and licenses included. */'}});
await esbuild.build({entryPoints:[path.join(root,'js/body-worker.js')],bundle:true,format:'iife',platform:'browser',target:['es2020'],outfile:path.join(root,'js/body-worker.bundle.js'),minify:true,legalComments:'eof'});
console.log('Built js/game.js with local curriculum, photos and Three.js. Optional model runtimes remain lazy.');
